# DRL BTC 自动交易系统配置文件

# 项目基础配置
project:
  name: "drl-btc-cloud"
  version: "1.0.0"
  description: "基于深度强化学习的BTC自动交易系统MVP"

# Google Cloud Platform 配置
gcp:
  # 项目配置
  project_id: "ai4fnew"  # 实际项目ID
  region: "asia-southeast1"       # 统一使用此区域
  
  # 存储配置
  storage:
    bucket_name: "ai4fnew-drl-btc-20250827"  # 统一bucket名称
    data_path: "data/"
    models_path: "models/ppo/"
    logs_path: "logs/paper/"
    
  # Vertex AI 配置
  vertex_ai:
    machine_type: "n1-standard-4"
    python_version: "3.9"
    container_uri: "gcr.io/cloud-aiplatform/training/pytorch-gpu.1-13.py39:latest"
    
  # Cloud Run 配置
  cloud_run:
    service_name: "drl-trader"
    memory: "2Gi"
    cpu: "2"
    timeout: "3600s"
    max_instances: 10
    
  # Pub/Sub 配置
  pubsub:
    topic_name: "drl-tick"
    
  # Cloud Scheduler 配置
  scheduler:
    job_name: "every-minute"
    schedule: "* * * * *"  # 每分钟触发
    
  # Eventarc 配置
  eventarc:
    trigger_name: "drl-trigger"

# 模型训练配置
training:
  total_timesteps: 100000
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  lookback: 60
  fee_rate: 0.001
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  
  # 训练数据配置
  data:
    symbol: "BTCUSDT"
    interval: "5m"
    days: 540  # 18个月历史数据
    
  # 验证配置
  validation:
    episodes: 5
    save_freq: 10000

# 推理服务配置
inference:
  # API配置
  api:
    host: "0.0.0.0"
    port: 8080
    workers: 1
    
  # 数据源配置  
  data_source:
    default: "binance"
    symbol: "BTCUSDT"
    interval: "1m"
    lookback: 60
    
  # 交易配置
  trading:
    initial_balance: 10000.0
    fee_rate: 0.001
    paper_trading: true
    
  # 缓存配置
  cache:
    price_update_seconds: 60
    model_reload_seconds: 300

# 数据获取配置 (cloudrun-fetch-data)
data_fetch:
  # 币安API配置
  binance:
    base_url: "https://api.binance.com"
    rate_limit: 1200  # 每分钟请求限制
    
  # 批处理配置
  batch:
    size: 1000
    retry_count: 3
    retry_delay: 2
    
  # 默认参数
  defaults:
    timeframe: "5m"
    days: 540
    save_gcs: true

# 监控和日志配置
monitoring:
  # Cloud Logging配置
  logging:
    level: "INFO"
    format: "json"
    
  # 健康检查配置
  health:
    check_interval: 300  # 5分钟
    timeout: 30
    
  # 性能指标
  metrics:
    collect_system: true
    collect_trading: true
    retention_days: 30

# 安全配置
security:
  # Secret Manager配置
  secrets:
    api_keys_secret: "trading-api-keys"
    
  # 权限配置
  iam:
    service_account: "drl-trader@ai4fnew.iam.gserviceaccount.com"